version: '3'

services:
###> doctrine/doctrine-bundle ###
  database:
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: peluqueria_venus
      MYSQL_USER: app
      MYSQL_PASSWORD: app
    ports:
      - "3306:3306"
    volumes:
      - database_data:/var/lib/mysql
###< doctrine/doctrine-bundle ###

###> MailHog (Para ver correos en local) ###
  mailer:
    image: mailhog/mailhog
    ports:
      - "1025:1025" # Puerto SMTP
      - "8025:8025" # Interfaz Web (http://localhost:8025)
###< MailHog ###

volumes:
  database_data: